// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8jEbCZ8KOb50x5DsxvW0ZkVmEDjr5QRU',
    appId: '1:580108180807:web:4e1d2f0e8debd8acd68062',
    messagingSenderId: '580108180807',
    projectId: 'studyplay-54bc1',
    authDomain: 'studyplay-54bc1.firebaseapp.com',
    storageBucket: 'studyplay-54bc1.firebasestorage.app',
    measurementId: 'G-J6LFKH7ZPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZwEDUJaLU-WS6gmSWznZpnG_9WoXsJj4',
    appId: '1:580108180807:android:bd6c2f166315ccd3d68062',
    messagingSenderId: '580108180807',
    projectId: 'studyplay-54bc1',
    storageBucket: 'studyplay-54bc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Dlu8IkKoTBA4imCG4_51XboKFvMwRak',
    appId: '1:580108180807:ios:526c767d4ee23cf4d68062',
    messagingSenderId: '580108180807',
    projectId: 'studyplay-54bc1',
    storageBucket: 'studyplay-54bc1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Dlu8IkKoTBA4imCG4_51XboKFvMwRak',
    appId: '1:580108180807:ios:526c767d4ee23cf4d68062',
    messagingSenderId: '580108180807',
    projectId: 'studyplay-54bc1',
    storageBucket: 'studyplay-54bc1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8jEbCZ8KOb50x5DsxvW0ZkVmEDjr5QRU',
    appId: '1:580108180807:web:e9198dd70c633f2ad68062',
    messagingSenderId: '580108180807',
    projectId: 'studyplay-54bc1',
    authDomain: 'studyplay-54bc1.firebaseapp.com',
    storageBucket: 'studyplay-54bc1.firebasestorage.app',
    measurementId: 'G-R967B2WCNJ',
  );
}
